#pragma kernel Main

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"

TEXTURE2D(Source);
RW_TEXTURE2D(float4, Destination);

[numthreads(8, 8, 1)]
void Main(uint2 id : SV_DispatchThreadID)
{
    uint width, height;
    Destination.GetDimensions(width, height);

    float2 col = (float2)id / float2(width, height);

    if (all(id < uint2(width, height)))
      Destination[id] = Source[id] + float4(col.xy, 0, 0);
}
